remote_theme: tuur29/pages-themes-cayman
plugins:
- jekyll-remote-theme
title: ML for molecules and materials in the era of LLMs [ML4Molecules]
description: ELLIS workshop, HYPRID, December 6, 2024
# ELLIS Machine Learning for Molecules Discovery workshop
