# remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: ML for molecules and materials in the era of LLMs [ML4Molecules]
description: ELLIS workshop, HYBRID, December 6, 2024
# ELLIS Machine Learning for Molecules Discovery workshop

# Customization options for Cayman theme
# theme: jekyll-theme-cayman

# Define the default layout for the site
defaults:
  - scope:
      path: ""  # An empty string means "all files"
    values:
      layout: default  # Use the custom layout in _layouts/default.html
